name: Build M3U

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Generate m3u
        run: python fix_names.py

      - name: Push to repo
        run: |
          git config --global user.name "bot"
          git config --global user.email "bot@example.com"
          git add output.m3u
          git diff --staged --exit-code || git commit -m "Update output.m3u"
          git push
